### PR TITLE
Add husky

### PR DESCRIPTION
**Pull request by M-Sieger**
- `npm install husky --save-dev && np husky init`
- `npm i -D lint-staged`
- Add `.lintstagedrc.json` with
- Edit `.husky/pre-commit`
- Add scripts for npm test
- Add pre-push with `npx husky add .husky/pre-push "npm test"`

- https://typicode.github.io/husky/#/

- https://github.com/okonet/lint-staged

### CODE REVIEW

**Review by fre-ben — APPROVED** [review]
LGTM 💯

**Review by christophvogel — APPROVED** [review]
LGTM 👍

**Review by JuKahl — APPROVED** [review]
GJ 🚀

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Pull request merged**
