### PR TITLE
➕ Add typescript

### PR DESCRIPTION
**Pull request by M-Sieger**
https://nextjs.org/docs/basic-features/typescript
- Add tsconfig.json
- Add typescript types

### CODE REVIEW

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by RonjaMeinecke — APPROVED** [review]
💪

**Review by m-wiemers — APPROVED** [review]
It seems that a new coach is born 👨‍💻

**Review by lmachens — APPROVED** [review]
🚀

**Comment by DNaunin** [comment]
LGTM! 🚀

**Pull request merged**
